BeFoundApp/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: "posts#index"

  resources :users, only: [:new, :create, :index, :show]
  resource :session, only: [:new, :create, :destroy]
end

BeFoundApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

BeFoundApp/app/models/post.rb
class Post < ApplicationRecord
end

BeFoundApp/app/models/user.rb
class User < ApplicationRecord
  PASSWORD_LENGTH = (6..25)
  USERNAME_LENGTH = (5..15)

  validates_presence_of :username
  validates :username, length: USERNAME_LENGTH, uniqueness: true

  validates :password, length: PASSWORD_LENGTH, allow_nil: true

  has_many :monsters

  attr_reader :password

  def self.find_from_credentials(username, password)
    user = find_by(username: username)
    return nil unless user
    user if user.is_password?(password)
  end

  def is_password?(password_attempt)
    BCrypt::Password.new(password_digest).is_password?(password_attempt)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
end

BeFoundApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
    helper_method :current_user
  
    private
  
    def sign_in(user)
      session[:session_token] = SecureRandom.urlsafe_base64
      user.update!(session_token: session[:session_token])
    end
  
    def sign_out
      return unless current_user
      current_user.update!(session_token: nil)
      session.delete(:session_token)
    end
  
    def current_user
      @current_user ||= find_current_user
    end
  
    def find_current_user
      session_token = session[:session_token]
      session_token && User.find_by(session_token: session_token)
    end
  
    def ensure_signed_in
      return if current_user
      flash[:error] = 'you must be signed in to see this'
      redirect_to :root
    end
  
    def ensure_signed_out
      return unless current_user
      flash[:error] = 'you are already signed in'
      redirect_to users_path
    end
end

BeFoundApp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_user, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      redirect_back fallback_location: edit_post_path(@post)
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:name,
                                 :photo,
                                 :missing_from,
                                 :date_missing,
                                 :sex,
                                 :ethnicity,
                                 :dob,
                                 :height,
                                 :weight,
                                 :eyes,
                                 :hair,
                                 :other,
                                 :photo)
  end

  def update_params
    params.require(:post).permit(:name,
                                 :photo,
                                 :missing_from,
                                 :date_missing,
                                 :sex,
                                 :ethnicity,
                                 :dob,
                                 :height,
                                 :weight,
                                 :eyes,
                                 :hair,
                                 :other,
                                 :photo)
  end

  def check_user
    unless current_user == @posts.user
      redirect_to root_path
    end
  end
end

BeFoundApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_signed_out, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    username = user_params[:username]
    password = user_params[:password]

    user = User.find_from_credentials(username, password)

    if user
      sign_in(user)
      flash[:notice] = "Hi, #{username}! You signed in!"
      redirect_to users_path
    else
      flash[:error] = 'User not found :('
      @user = User.new(username: username)
      render :new
    end
  end

  def destroy
    sign_out
    flash[:notice] = 'You signed out!'
    redirect_to new_session_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

BeFoundApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_signed_out, only: %i[new create]
  before_action :ensure_signed_in, only: %i[show index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)

    if @user.save
      sign_in(@user)
      flash[:notice] = 'You are now sign in!'
      redirect_to users_path
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def create_params
    params.require(:user).permit(:username, :password)
  end
end

BeFoundApp/app/helpers/application_helper.rb
module ApplicationHelper
end

BeFoundApp/app/helpers/posts_helper.rb
module PostsHelper
end

BeFoundApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

BeFoundApp/app/helpers/users_helper.rb
module UsersHelper
end

BeFoundApp/app/views/layouts/_footer.html.erb
<div class="container pt-4">
<hr>
</div>
<footer>
  <div>
    <div class="container pt-4">
      <div class="row">
        <div class="footer-col col-md-4 text-center">
          <h3>BeFound</h3>
          <p>BeFound was created as a source to find missing individual that will provide as a means to help to report missing
            people in the United Assembly.</p>
        </div>
        <div class="footer-col col-md-4 text-center">
          <h3>Contact Us</h3>
          <p>212-646-6699</p>
        </div>
        <div class="footer-col col-md-4 text-center">
          <h3>Please Read</h3>
          <p>We obtain permisson to the missing person/s family to display photos and information of their loveones. If you
            have any questions or concern please let us know</p>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-below">
    <div class="container pt-4">
      <div class="row text-center">
        <div class="col-lg-12">
          Copyright &copy; BeFound 2017
        </div>
        <br><br>
      </div>
    </div>
  </div>
</footer>

BeFoundApp/app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-faded fixed-top">
  <div class="container">
    <%= link_to "BeFound", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <%= link_to "Add post",new_post_path, class: "nav-link" %>
        </li>
        <!-- <li class="nav-item">
          <a class="nav-link" href="#">Sign In
              <span class="sr-only">(current)</span>
            </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Register</a>
        </li> -->
      </ul>
    </div>
  </div>
</nav>

BeFoundApp/app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-faded fixed-top">
  <div class="container">
    <%= link_to "BeFound", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <%= link_to "Add post", new_post_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", session_path, method: :delete, class: "nav-link" %>
          <span class="sr-only">(current)</span>
        </li>
      </ul>
    </div> 
  </div>
</nav>

BeFoundApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeFoundApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render "layouts/nav" %>

      <div class="container pt-4">
      <!-- <% if current_user %>
        <%= link_to current_user.username, user_path(current_user) %> signed in
        <%= button_to 'Log out', session_path, method: :delete %>
      <% end %> -->

      <% if flash[:notice].present? %>
        <div class="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:error].present? %>
        <div class="errors">
          <b>Errors:</b>
          <%= flash[:error] %>
        </div>
      <% end %>
    </div>
    <%= yield %>

    <%= render "layouts/footer" %>

  </body>
</html>

BeFoundApp/app/views/partials/_post_form.html.erb
<div class="container pt-4">
  <%= form_for @post do |f| %>
    <form>
      <div class="form-row">
        <div class="form-group col-sm-12">
          <%= f.label :name, class: "col-form-label" %>
          <%= f.text_field :name, class: "form-control", placeholder: "Firstname and Lastname"%>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-sm-12 col-lg-6">
          <%= f.label :missing_from, class: "col-form-label" %>
          <%= f.text_field :missing_from, class: "form-control", placeholder: "City, State"%>
        </div>
        <div class="form-group col-sm-12 col-lg-6">
          <%= f.label :date_missing, class: "col-form-label" %>
          <%= f.text_field :date_missing, class: "form-control"%>
        </div>
      </div>
      <div class="form-row">
          <div class="form-group col-sm-12 col-lg-4">
            <%= f.label :dob, class: "col-form-label" %>
            <%= f.text_field :dob, class: "form-control"%>
          </div>
          <div class="form-group col-sm-12 col-lg-4">
            <%= f.label :sex, class: "col-form-label" %>
            <!-- <%= select_tag :sex,  class: "form-control"%> -->
            <%= f.select :sex, options_for_select([["Select One", ""], "Male", "Female", "Other"]), class: "form-control" %>
          </div>
          <div class="form-group col-sm-12 col-lg-4">
            <%= f.label :ethnicity, class: "col-form-label" %>
            <%= f.text_field :ethnicity, class: "form-control"%>
          </div>
      </div>
      <div class="form-row">
          <div class="form-group col-sm-12 col-lg-3">
            <%= f.label :height, class: "col-form-label" %>
            <%= f.text_field :height, class: "form-control", placeholder: "in centimeter"%>
          </div>
          <div class="form-group col-sm-12 col-lg-3">
            <%= f.label :weight, class: "col-form-label" %>
            <%= f.text_field :weight, class: "form-control", placeholder: "in gms"%>
          </div>
          <div class="form-group col-sm-12 col-lg-3">
            <%= f.label :eyes, class: "col-form-label" %>
            <%= f.text_field :eyes, class: "form-control"%>
          </div>
          <div class="form-group col-sm-12 col-lg-3">
            <%= f.label :hair, class: "col-form-label" %>
            <%= f.text_field :hair, class: "form-control"%>
          </div>
      </div>
      <div class="form-row">
          <div class="form-group col-sm-12">
            <%= f.label :photo, class: "col-form-label" %>
            <%= f.text_field :photo, class: "form-control", placeholder: "Image goes here"%>
          </div>
        </div>
      <div class="form-row">
          <div class="form-group col">
            <%= f.label :other, class: "col-form-label" %>
            <%= f.text_area :other, class: "form-control", rows: "10" %>
          </div>
      </div>
   
      <%= f.submit class: "btn btn-primary", value: "Submit" %>
    </form>
  </div>
<% end %>

BeFoundApp/app/views/posts/edit.html.erb
<%= render "layouts/nav_user" %>
<div class="container pt-4">
  <h1>Edit Post</h1>
  <%= render "partials/post_form" %>
</div>

BeFoundApp/app/views/posts/index.html.erb
<header class="jumbotron my-5 text-center pt-4">
  <h1 class="display-2">HAVE YOU SEEN ME?</h1>
  <p class="lead">Listed below are some of the missing persons currently reported in the State of New Assembly. To see more information on
    each missing person, click on More Info. If you have a tip or would like to add a case to the web site.</p>
  <p>call the New Assembly State Police:</p>
  <p>Missing Persons Unit at #212-832-9870, extension x24</p>
</header>

<div class="container">
  <% @posts.each do |post| %>
    <div class="row">
      <div class="col-md-7">
        <a><img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="photo will goes here"></a>
      </div>
      <div class="col-md-5">
        <h3><%= post.name %></h3>
        <p><%= post.date_missing %></p>
        <p><%= post.sex %></p>
        <br>
        <p><%= link_to  "more info", post, class: "btn btn-primary" %></p>
        <small>posted <%= time_ago_in_words(post.created_at) %> ago</small>
      </div>
    </div>
    <br><hr><br>
  <% end %>
  </div>>

BeFoundApp/app/views/posts/new.html.erb
<%= render "layouts/nav_user" %>
<div class="container pt-4">
  <h1>Missing Person Information</h1>
  <%= render "partials/post_form" %>
</div>

BeFoundApp/app/views/posts/show.html.erb
<%= render "layouts/nav_user" %>
<div class="container pt-4">
  <h1><%= @post.name %></h1>
  <p><%= @post.photo %></p>
  <p><%= @post.missing_from %></p>
  <p><%= @post.date_missing %></p>
  <p><%= @post.dob %></p>
  <p><%= @post.sex %></p>
  <p><%= @post.ethnicity %></p>
  <p><%= @post.height %></p>
  <p><%= @post.weight %></p>
  <p><%= @post.eyes %></p>
  <p><%= @post.hair %></p>
  <p><%= @post.photo %></p>
  <p><%= @post.other %></p>
  <small>posted <%= time_ago_in_words(@post.created_at) %> ago</small><br><br>

  <div class="btn-group" role="group" aria-label="Basic example">
    <%= link_to "edit", edit_post_path(@post), class: "btn btn-primary btn-sm" %>
    <%= link_to "delete", post_path(@post), method: :delete, class: "btn btn-danger btn-sm" %>
  </div>

</div>

BeFoundApp/app/views/users/index.html.erb
<%= render "layouts/nav_user" %>
<div class="container pt-4">
<h3>Users</h3>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, user_path(user) %>
    </li>
    <% end %>
</ul>
</div>

BeFoundApp/app/views/users/new.html.erb
<%= render "layouts/nav" %>
<div class="container pt-4">
<h2> Create an account </h2>

<%= form_for @user do |form| %>
  <%= form.text_field :username,
        placeholder: 'Username',
        required: true,
        minlength: User::USERNAME_LENGTH.begin,
        maxlength: User::USERNAME_LENGTH.end
  %>

  <%= form.password_field :password,
        placeholder: 'password',
        required: true,
        minlength: User::PASSWORD_LENGTH.begin,
        maxlength: User::PASSWORD_LENGTH.end
  %>

  <%= submit_tag 'Create Account!' %>
<% end %>

<br>
Returning user? <%= link_to 'Sign in', new_session_path %>
</div>

BeFoundApp/app/views/users/show.html.erb
<%= render "layouts/nav_user" %>
<div class="container pt-4">
<h1><%= @user.username %></h1>


<h2>This is your dashboard</h2>

<br>

<%= link_to 'user_path', users_path %>
</div>